name       : tuxmath
version    : 2.0.3
release    : 4
source     :
    - https://github.com/tux4kids/tuxmath/archive/refs/tags/upstream/2.0.3.tar.gz : ab91bd6df17eb9377e5608701030bd32110a3588933bf0e4c26b5697fb2a4698
license    : GPL-3.0
component  : games.learning
summary    : An arcade game that helps kids practice their math facts
description: |
    An arcade game that helps kids practice their math facts
builddeps  :
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(t4k_common)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-building.patch
    %patch -p1 < $pkgfiles/0002-rename-blits-to-tmblits.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 tuxmath.desktop $installdir/usr/share/applications/tuxmath.desktop
    install -D -m 00644 data/images/icons/icon.png $installdir/usr/share/pixmaps/tuxmath.png
