name       : tuxmath
version    : 2.0.3
release    : 1
source     :
    - http://distro.ibiblio.org/slitaz/sources/packages/t/tuxmath_w_fonts-2.0.3.tar.gz : eec49c296d41df39a6474d94ba4e3334e4c16dc180d3ea4a6defc2debfc39887
license    : GPL-3.0
component  : games.learning
summary    : An arcade game that helps kids practice their math facts
description: |
    An arcade game that helps kids practice their math facts
builddeps  :
    - pkgconfig(t4k_common)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 tuxmath.desktop $installdir/usr/share/applications/tuxmath.desktop
    install -D -m 00644 data/images/icons/icon.png $installdir/usr/share/pixmaps/tuxmath.png
